#!/bin/bash

#Declare Variables

HEIGHT=15
WIDTH=60
CHOICE_HEIGHT=4
BACKTITLE="Shutdown-Dialog"
TITLE="Shutdown"

MENU="Choose one of the following options:"
OPTIONS=(1 "Option 1: Shutdown"
         2 "Option 2: Reboot")

#DIALOG CHOOSE OPTIONS

clear

CHOICE=$(dialog --clear \
                --backtitle "$BACKTITLE" \
                --title "$TITLE" \
                --menu "$MENU" \
                $HEIGHT $WIDTH $CHOICE_HEIGHT \
                "${OPTIONS[@]}" \
                2>&1 >/dev/tty)


case $CHOICE in
        
0) 
exit
1)
shutdown -h -P now


            ;;
        2)
reboot

            ;;
esac

#jonisc

